<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>adi_tmc_coe_core</name>
  <version>1.0.0</version>
  <description>Core package for Trinamic Motor Controllers (TMC) that uses CANopen-over-etherCAT(CoE) protocol.</description>
  <maintainer email="ROS@analog.com">Analog Devices</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rclcpp</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>libcap-dev</build_depend>

  <depend>adi_tmc_coe_interfaces</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <exec_depend>libcap-dev</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
