# Copyright (c) 2024 Analog Devices, Inc. All Rights Reserved.
# This software is proprietary to Analog Devices, Inc. and its licensors.

import os

from launch import LaunchDescription
from launch_ros.actions import Node
from launch.substitutions import (LaunchConfiguration, PythonExpression)
from launch.actions import DeclareLaunchArgument
from ament_index_python.packages import get_package_share_directory

def generate_launch_description():
  ## Get directory of config files
  adi_tmc_coe_ros2_pkg_dir = get_package_share_directory('adi_tmc_coe_core')
  ## Include YAML file
  autogenerated_yaml = os.path.join(adi_tmc_coe_ros2_pkg_dir, 'config', 'autogenerated', 'TMCM-1461.yaml')
  ext_yaml = os.path.join(adi_tmc_coe_ros2_pkg_dir, 'config', '2slave_1axis_per_slave.yaml')

  # Declare the Launch Arguments with default value
  arg_log_level = DeclareLaunchArgument('log_level', default_value='INFO')
  log_level_ = LaunchConfiguration('log_level')

  arg_ns_prefix = DeclareLaunchArgument('ns_prefix', default_value='tmc_coe1')
  ns_prefix_ = LaunchConfiguration('ns_prefix')

  # Base name for the 2 Slaves
  arg_tmc_base_name1 = DeclareLaunchArgument('tmc_base_name1', default_value='tmcm_1461_1')
  arg_tmc_base_name2 = DeclareLaunchArgument('tmc_base_name2', default_value='tmcm_1461_2')
  tmc_base_name1_ = LaunchConfiguration('tmc_base_name1')
  tmc_base_name2_ = LaunchConfiguration('tmc_base_name2')

  # Frames for Slave 1
  arg_board1_parent_frame = DeclareLaunchArgument('board1_parent_frame', default_value='map')
  arg_board1_base_name = DeclareLaunchArgument('board1_base_name', default_value=[ns_prefix_,'/',tmc_base_name1_,'_base_link'])
  arg_board1_pos_x = DeclareLaunchArgument('board1_pos_x', default_value='0')
  arg_board1_pos_y = DeclareLaunchArgument('board1_pos_y', default_value='0')
  arg_board1_pos_z = DeclareLaunchArgument('board1_pos_z', default_value='0')
  arg_board1_pos_qx = DeclareLaunchArgument('board1_pos_qx', default_value='0')
  arg_board1_pos_qy = DeclareLaunchArgument('board1_pos_qy', default_value='0')
  arg_board1_pos_qz = DeclareLaunchArgument('board1_pos_qz', default_value='0')
  arg_board1_pos_qw = DeclareLaunchArgument('board1_pos_qw', default_value='1')

  board1_parent_frame_ = LaunchConfiguration('board1_parent_frame')
  board1_base_name_ = LaunchConfiguration('board1_base_name')
  board1_pos_x_ = LaunchConfiguration('board1_pos_x')
  board1_pos_y_ = LaunchConfiguration('board1_pos_y')
  board1_pos_z_ = LaunchConfiguration('board1_pos_z')
  board1_pos_qx_ = LaunchConfiguration('board1_pos_qx')
  board1_pos_qy_ = LaunchConfiguration('board1_pos_qy')
  board1_pos_qz_ = LaunchConfiguration('board1_pos_qz')
  board1_pos_qw_ = LaunchConfiguration('board1_pos_qw')
  # Slave 1 motor0 Arguments
  arg_board1_mtr0_base_name = DeclareLaunchArgument('board1_mtr0_base_name', default_value=[ns_prefix_,'/',tmc_base_name1_,'_mtr0_frame'])
  arg_board1_mtr0_pos_x = DeclareLaunchArgument('board1_mtr0_pos_x', default_value='0')
  arg_board1_mtr0_pos_y = DeclareLaunchArgument('board1_mtr0_pos_y', default_value='1')
  arg_board1_mtr0_pos_z = DeclareLaunchArgument('board1_mtr0_pos_z', default_value='0')
  arg_board1_mtr0_pos_qx = DeclareLaunchArgument('board1_mtr0_pos_qx', default_value='0')
  arg_board1_mtr0_pos_qy = DeclareLaunchArgument('board1_mtr0_pos_qy', default_value='0')
  arg_board1_mtr0_pos_qz = DeclareLaunchArgument('board1_mtr0_pos_qz', default_value='0')
  arg_board1_mtr0_pos_qw = DeclareLaunchArgument('board1_mtr0_pos_qw', default_value='1')

  board1_mtr0_base_name_ = LaunchConfiguration('board1_mtr0_base_name')
  board1_mtr0_pos_x_ = LaunchConfiguration('board1_mtr0_pos_x')
  board1_mtr0_pos_y_ = LaunchConfiguration('board1_mtr0_pos_y')
  board1_mtr0_pos_z_ = LaunchConfiguration('board1_mtr0_pos_z')
  board1_mtr0_pos_qx_ = LaunchConfiguration('board1_mtr0_pos_qx')
  board1_mtr0_pos_qy_ = LaunchConfiguration('board1_mtr0_pos_qy')
  board1_mtr0_pos_qz_ = LaunchConfiguration('board1_mtr0_pos_qz')
  board1_mtr0_pos_qw_ = LaunchConfiguration('board1_mtr0_pos_qw')

  # Frames for Slave 2
  arg_board2_parent_frame = DeclareLaunchArgument('board2_parent_frame', default_value='map')
  arg_board2_base_name = DeclareLaunchArgument('board2_base_name', default_value=[ns_prefix_,'/',tmc_base_name2_,'_base_link'])
  arg_board2_pos_x = DeclareLaunchArgument('board2_pos_x', default_value='0')
  arg_board2_pos_y = DeclareLaunchArgument('board2_pos_y', default_value='0')
  arg_board2_pos_z = DeclareLaunchArgument('board2_pos_z', default_value='0')
  arg_board2_pos_qx = DeclareLaunchArgument('board2_pos_qx', default_value='0')
  arg_board2_pos_qy = DeclareLaunchArgument('board2_pos_qy', default_value='0')
  arg_board2_pos_qz = DeclareLaunchArgument('board2_pos_qz', default_value='0')
  arg_board2_pos_qw = DeclareLaunchArgument('board2_pos_qw', default_value='1')

  board2_parent_frame_ = LaunchConfiguration('board2_parent_frame')
  board2_base_name_ = LaunchConfiguration('board2_base_name')
  board2_pos_x_ = LaunchConfiguration('board2_pos_x')
  board2_pos_y_ = LaunchConfiguration('board2_pos_y')
  board2_pos_z_ = LaunchConfiguration('board2_pos_z')
  board2_pos_qx_ = LaunchConfiguration('board2_pos_qx')
  board2_pos_qy_ = LaunchConfiguration('board2_pos_qy')
  board2_pos_qz_ = LaunchConfiguration('board2_pos_qz')
  board2_pos_qw_ = LaunchConfiguration('board2_pos_qw')
  # Slave 2 motor0 Arguments
  arg_board2_mtr0_base_name = DeclareLaunchArgument('board2_mtr0_base_name', default_value=[ns_prefix_,'/',tmc_base_name2_,'_mtr0_frame'])
  arg_board2_mtr0_pos_x = DeclareLaunchArgument('board2_mtr0_pos_x', default_value='0')
  arg_board2_mtr0_pos_y = DeclareLaunchArgument('board2_mtr0_pos_y', default_value='1')
  arg_board2_mtr0_pos_z = DeclareLaunchArgument('board2_mtr0_pos_z', default_value='0')
  arg_board2_mtr0_pos_qx = DeclareLaunchArgument('board2_mtr0_pos_qx', default_value='0')
  arg_board2_mtr0_pos_qy = DeclareLaunchArgument('board2_mtr0_pos_qy', default_value='0')
  arg_board2_mtr0_pos_qz = DeclareLaunchArgument('board2_mtr0_pos_qz', default_value='0')
  arg_board2_mtr0_pos_qw = DeclareLaunchArgument('board2_mtr0_pos_qw', default_value='1')

  board2_mtr0_base_name_ = LaunchConfiguration('board2_mtr0_base_name')
  board2_mtr0_pos_x_ = LaunchConfiguration('board2_mtr0_pos_x')
  board2_mtr0_pos_y_ = LaunchConfiguration('board2_mtr0_pos_y')
  board2_mtr0_pos_z_ = LaunchConfiguration('board2_mtr0_pos_z')
  board2_mtr0_pos_qx_ = LaunchConfiguration('board2_mtr0_pos_qx')
  board2_mtr0_pos_qy_ = LaunchConfiguration('board2_mtr0_pos_qy')
  board2_mtr0_pos_qz_ = LaunchConfiguration('board2_mtr0_pos_qz')
  board2_mtr0_pos_qw_ = LaunchConfiguration('board2_mtr0_pos_qw')


  # ADI TMC COE ROS2 Node
  tmc_coe_node = Node(
    package="adi_tmc_coe_core",
    executable="tmc_coe_ros2_node",
    name="tmc_coe_ros2_node",
    namespace=ns_prefix_,
    emulate_tty=True,
    prefix=["adi_ethercat_grant_node"],
    parameters=[
      autogenerated_yaml,
      ext_yaml],
    arguments=["--ros-args", "--log-level", PythonExpression(expression=["'",ns_prefix_,".tmc_coe_ros2_node:=",log_level_,"'"])]
  )

  # TF Node for Slave 1
  tf_board1 = Node(
    package="tf2_ros",
    executable="static_transform_publisher",
    name=[tmc_base_name1_,'_link'],
    namespace=ns_prefix_,
    emulate_tty=True,
    arguments=["--x", board1_pos_x_, "--y", board1_pos_y_, "--z", board1_pos_z_,
      "--qx", board1_pos_qx_, "--qy", board1_pos_qy_, "--qz", board1_pos_qz_, "--qw", board1_pos_qw_,
      "--frame-id", board1_parent_frame_, "--child-frame-id", board1_base_name_]
  )

  tf_board1_mtr0 = Node(
    package="tf2_ros",
    executable="static_transform_publisher",
    name=[tmc_base_name1_,'_mtr0_link'],
    namespace=ns_prefix_,
    emulate_tty=True,
    arguments=["--x", board1_mtr0_pos_x_, "--y", board1_mtr0_pos_y_, "--z", board1_mtr0_pos_z_,
      "--qx", board1_mtr0_pos_qx_, "--qy", board1_mtr0_pos_qy_, "--qz", board1_mtr0_pos_qz_, "--qw", board1_mtr0_pos_qw_,
      "--frame-id", board1_base_name_, "--child-frame-id", board1_mtr0_base_name_]
  )

  # TF Node for Slave 2
  tf_board2 = Node(
    package="tf2_ros",
    executable="static_transform_publisher",
    name=[tmc_base_name1_,'_link'],
    namespace=ns_prefix_,
    emulate_tty=True,
    arguments=["--x", board2_pos_x_, "--y", board2_pos_y_, "--z", board2_pos_z_,
      "--qx", board2_pos_qx_, "--qy", board2_pos_qy_, "--qz", board2_pos_qz_, "--qw", board2_pos_qw_,
      "--frame-id", board2_parent_frame_, "--child-frame-id", board2_base_name_]
  )

  tf_board2_mtr0 = Node(
    package="tf2_ros",
    executable="static_transform_publisher",
    name=[tmc_base_name1_,'_mtr0_link'],
    namespace=ns_prefix_,
    emulate_tty=True,
    arguments=["--x", board2_mtr0_pos_x_, "--y", board2_mtr0_pos_y_, "--z", board2_mtr0_pos_z_,
      "--qx", board2_mtr0_pos_qx_, "--qy", board2_mtr0_pos_qy_, "--qz", board2_mtr0_pos_qz_, "--qw", board2_mtr0_pos_qw_,
      "--frame-id", board2_base_name_, "--child-frame-id", board2_mtr0_base_name_]
  )

  return LaunchDescription([
      arg_log_level,
      arg_ns_prefix,
      arg_tmc_base_name1,
      arg_board1_parent_frame,
      arg_board1_base_name,arg_board1_pos_x, arg_board1_pos_y, arg_board1_pos_z, arg_board1_pos_qx, arg_board1_pos_qy, arg_board1_pos_qz, arg_board1_pos_qw,
      arg_board1_mtr0_base_name, arg_board1_mtr0_pos_x, arg_board1_mtr0_pos_y, arg_board1_mtr0_pos_z, arg_board1_mtr0_pos_qx, arg_board1_mtr0_pos_qy, arg_board1_mtr0_pos_qz, arg_board1_mtr0_pos_qw,
      arg_tmc_base_name2,
      arg_board2_parent_frame,
      arg_board2_base_name,arg_board2_pos_x, arg_board2_pos_y, arg_board2_pos_z, arg_board2_pos_qx, arg_board2_pos_qy, arg_board2_pos_qz, arg_board2_pos_qw,
      arg_board2_mtr0_base_name, arg_board2_mtr0_pos_x, arg_board2_mtr0_pos_y, arg_board2_mtr0_pos_z, arg_board2_mtr0_pos_qx, arg_board2_mtr0_pos_qy, arg_board2_mtr0_pos_qz, arg_board2_mtr0_pos_qw,
      tmc_coe_node,
      tf_board1,
      tf_board1_mtr0,
      tf_board2,
      tf_board2_mtr0
  ])
